# Generated by Django 4.2.1 on 2023-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendslider',
            name='image',
            field=models.ImageField(upload_to='uploads/slider_images/'),
        ),
    ]
