# Generated by Django 4.2.1 on 2023-06-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('num_adults', models.IntegerField()),
                ('num_childrens', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
            ],
        ),
    ]
