# Generated by Django 4.2.1 on 2023-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_card_details_alter_carouselimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/slider')),
                ('caption', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CarouselImage',
        ),
    ]
