# Generated by Django 4.2.1 on 2023-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_slider_delete_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Available'), ('NA', 'Not Available')], default='P', max_length=2),
        ),
    ]
